### ISSUE TITLE
We should be able to manipulate the generated markdown

### ISSUE THREAD

**Issue by Ma7eer** [Maher9596/Checklist#15]

**Comment by Maher9596** [comment]
# Test manipulating the HTML
- I did this test by **consol.log** the generated HTML and by changing the HTML content using *innerHTML* as show in the picture below.

![image](https://user-images.githubusercontent.com/72282480/99577018-2ab20180-29f4-11eb-8c9c-66a55b0374ae.png)

**Comment by Ma7eer** [comment]
Test this by creating a js file and manipulating the text from there.
