### ISSUE TITLE
MD text area (Suggestion)

### ISSUE THREAD

**Issue by Maher9596** [Maher9596/Checklist#20]
## Current plan 
For now the plan is to write the notes in a Markdown file locally and then upload to our site.

## Suggestion 
I think we should consider the option of adding a **Markdown text area** to our site.

## Benefits
- Avoid relaying on external apps
- Better user and admin experience 
- Eliminate risk of attacker uploading malicious code to the web server

## Risks
-  We will be at risk of XSS vulnerabilities, However I believe we can manage this risk by sanitizing our input by calling** strip_tags()**

## Example of a MD text area
![image](https://user-images.githubusercontent.com/72282480/99112966-ebf10580-2607-11eb-9cf8-fb9628b57d9e.png)

**Comment by Ma7eer** [comment]
hmmm I am convinced. Fine for now we will change direction and remove the upload functionality. I will add an issue on this and close any issues related to upload.

**Comment by Ma7eer** [comment]
Since we agree on this, I will close it.
