### ISSUE TITLE
PRs should not be allowed to be merged without a review

### ISSUE THREAD

**Issue by Ma7eer** [Maher9596/Checklist#25]
@Maher9596  only you can do this as you are the project administrator. You can set up the force review functionality by following the instructions on this [link](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-required-reviews-for-pull-requests)

**Comment by Maher9596** [comment]
I have updated the **development** branch settings, PRs can no longer be merged without a review.

We can close this issue.
